version: '2'
services:

  web:
    container_name: waproject-api
    build: docker/dev
    ports:
      - "3001:3000"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database
    networks: 
      - backend

  database:
    container_name: waproject-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=waproject
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks: 
      - backend
  
networks: 
  backend: 
    driver: 'bridge'